- path: /certificateBasedAuthConfiguration
  path_description: Provides operations to manage the collection of certificateBasedAuthConfiguration entities.
  path_parameters: []
  methods:
  - method: GET
    summary: Get entities from certificateBasedAuthConfiguration
    description: No description provided.
    parameters:
    - $ref: '#/components/parameters/top'
    - $ref: '#/components/parameters/skip'
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    - $ref: '#/components/parameters/count'
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
  - method: POST
    summary: Add new entity to certificateBasedAuthConfiguration
    description: No description provided.
    parameters: []
    requestBody:
      description: New entity
      required: true
      schema:
        allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: certificateBasedAuthConfiguration
          required:
          - '@odata.type'
          type: object
          properties:
            certificateAuthorities:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.certificateAuthority'
              description: Collection of certificate authorities which creates a trusted certificate chain.
            '@odata.type':
              type: string
        x-ms-discriminator-value: '#microsoft.graph.certificateBasedAuthConfiguration'
- path: /certificateBasedAuthConfiguration/{certificateBasedAuthConfiguration-id}
  path_description: Provides operations to manage the collection of certificateBasedAuthConfiguration entities.
  path_parameters:
  - name: certificateBasedAuthConfiguration-id
    in: path
    description: The unique identifier of certificateBasedAuthConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: certificateBasedAuthConfiguration
  methods:
  - method: GET
    summary: Get entity from certificateBasedAuthConfiguration by key
    description: No description provided.
    parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
  - method: PATCH
    summary: Update entity in certificateBasedAuthConfiguration
    description: No description provided.
    parameters: []
    requestBody:
      description: New property values
      required: true
      schema:
        allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: certificateBasedAuthConfiguration
          required:
          - '@odata.type'
          type: object
          properties:
            certificateAuthorities:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.certificateAuthority'
              description: Collection of certificate authorities which creates a trusted certificate chain.
            '@odata.type':
              type: string
        x-ms-discriminator-value: '#microsoft.graph.certificateBasedAuthConfiguration'
  - method: DELETE
    summary: Delete entity from certificateBasedAuthConfiguration
    description: No description provided.
    parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
    requestBody: null
- path: /certificateBasedAuthConfiguration/$count
  path_description: Provides operations to count the resources in the collection.
  path_parameters: []
  methods:
  - method: GET
    summary: Get the number of the resource
    description: No description provided.
    parameters:
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    requestBody: null
