- path: /authenticationMethodConfigurations
  path_description: Provides operations to manage the collection of authenticationMethodConfiguration entities.
  path_parameters: []
  methods:
  - method: GET
    summary: Get entities from authenticationMethodConfigurations
    description: No description provided.
    parameters:
    - $ref: '#/components/parameters/top'
    - $ref: '#/components/parameters/skip'
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    - $ref: '#/components/parameters/count'
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
  - method: POST
    summary: Add new entity to authenticationMethodConfigurations
    description: No description provided.
    parameters: []
    requestBody:
      description: New entity
      required: true
      schema:
        allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: authenticationMethodConfiguration
          required:
          - '@odata.type'
          type: object
          properties:
            excludeTargets:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.excludeTarget'
              description: Groups of users that are excluded from a policy.
            state:
              anyOf:
              - $ref: '#/components/schemas/microsoft.graph.authenticationMethodState'
              - type: object
                nullable: true
              description: 'The state of the policy. Possible values are: enabled, disabled.'
            '@odata.type':
              type: string
          discriminator:
            propertyName: '@odata.type'
            mapping:
              '#microsoft.graph.emailAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.emailAuthenticationMethodConfiguration'
              '#microsoft.graph.fido2AuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.fido2AuthenticationMethodConfiguration'
              '#microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration'
              '#microsoft.graph.smsAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.smsAuthenticationMethodConfiguration'
              '#microsoft.graph.softwareOathAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.softwareOathAuthenticationMethodConfiguration'
              '#microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration'
              '#microsoft.graph.voiceAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.voiceAuthenticationMethodConfiguration'
              '#microsoft.graph.x509CertificateAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.x509CertificateAuthenticationMethodConfiguration'
- path: /authenticationMethodConfigurations/{authenticationMethodConfiguration-id}
  path_description: Provides operations to manage the collection of authenticationMethodConfiguration entities.
  path_parameters:
  - name: authenticationMethodConfiguration-id
    in: path
    description: The unique identifier of authenticationMethodConfiguration
    required: true
    schema:
      type: string
    x-ms-docs-key-type: authenticationMethodConfiguration
  methods:
  - method: GET
    summary: Get entity from authenticationMethodConfigurations by key
    description: No description provided.
    parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
  - method: PATCH
    summary: Update entity in authenticationMethodConfigurations
    description: No description provided.
    parameters: []
    requestBody:
      description: New property values
      required: true
      schema:
        allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: authenticationMethodConfiguration
          required:
          - '@odata.type'
          type: object
          properties:
            excludeTargets:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.excludeTarget'
              description: Groups of users that are excluded from a policy.
            state:
              anyOf:
              - $ref: '#/components/schemas/microsoft.graph.authenticationMethodState'
              - type: object
                nullable: true
              description: 'The state of the policy. Possible values are: enabled, disabled.'
            '@odata.type':
              type: string
          discriminator:
            propertyName: '@odata.type'
            mapping:
              '#microsoft.graph.emailAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.emailAuthenticationMethodConfiguration'
              '#microsoft.graph.fido2AuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.fido2AuthenticationMethodConfiguration'
              '#microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.microsoftAuthenticatorAuthenticationMethodConfiguration'
              '#microsoft.graph.smsAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.smsAuthenticationMethodConfiguration'
              '#microsoft.graph.softwareOathAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.softwareOathAuthenticationMethodConfiguration'
              '#microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.temporaryAccessPassAuthenticationMethodConfiguration'
              '#microsoft.graph.voiceAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.voiceAuthenticationMethodConfiguration'
              '#microsoft.graph.x509CertificateAuthenticationMethodConfiguration': '#/components/schemas/microsoft.graph.x509CertificateAuthenticationMethodConfiguration'
  - method: DELETE
    summary: Delete entity from authenticationMethodConfigurations
    description: No description provided.
    parameters:
    - name: If-Match
      in: header
      description: ETag
      schema:
        type: string
    requestBody: null
- path: /authenticationMethodConfigurations/$count
  path_description: Provides operations to count the resources in the collection.
  path_parameters: []
  methods:
  - method: GET
    summary: Get the number of the resource
    description: No description provided.
    parameters:
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    requestBody: null
