- path: /applicationTemplates
  path_description: Provides operations to manage the collection of applicationTemplate entities.
  path_parameters: []
  methods:
  - method: GET
    summary: List applicationTemplates
    description: Retrieve a list of applicationTemplate objects from the Microsoft Entra application gallery.
    parameters:
    - $ref: '#/components/parameters/top'
    - $ref: '#/components/parameters/skip'
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    - $ref: '#/components/parameters/count'
    - name: $orderby
      in: query
      description: Order items by property values
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
- path: /applicationTemplates/{applicationTemplate-id}
  path_description: Provides operations to manage the collection of applicationTemplate entities.
  path_parameters:
  - name: applicationTemplate-id
    in: path
    description: The unique identifier of applicationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: applicationTemplate
  methods:
  - method: GET
    summary: Get applicationTemplate
    description: Retrieve the properties of an applicationTemplate object.
    parameters:
    - name: $select
      in: query
      description: Select properties to be returned
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    - name: $expand
      in: query
      description: Expand related entities
      style: form
      explode: false
      schema:
        uniqueItems: true
        type: array
        items:
          type: string
    requestBody: null
- path: /applicationTemplates/{applicationTemplate-id}/instantiate
  path_description: Provides operations to call the instantiate method.
  path_parameters:
  - name: applicationTemplate-id
    in: path
    description: The unique identifier of applicationTemplate
    required: true
    schema:
      type: string
    x-ms-docs-key-type: applicationTemplate
  methods:
  - method: POST
    summary: Invoke action instantiate
    description: Add an instance of an application from the Microsoft Entra application gallery into your directory. For non-gallery apps, use an application template with one of the following IDs to configure different single sign-on (SSO) modes like SAML SSO and password-based SSO.
    parameters: []
    requestBody:
      description: Action parameters
      required: true
      schema:
        type: object
        properties:
          displayName:
            type: string
            nullable: true
          serviceManagementReference:
            type: string
            nullable: true
- path: /applicationTemplates/$count
  path_description: Provides operations to count the resources in the collection.
  path_parameters: []
  methods:
  - method: GET
    summary: Get the number of the resource
    description: No description provided.
    parameters:
    - $ref: '#/components/parameters/search'
    - $ref: '#/components/parameters/filter'
    requestBody: null
